spring:
  datasource:
#    url: jdbc:h2:file:./data/chatmemory;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:testdb
    username: gautam
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ai
  ai:
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: GAUTAM
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always  # table will be created automatically (SPRING_AI_CHAT_MEMORY to store chat history)
      client:
        enabled: false        # to use multimodels At same time
    openai:                   # config for openAi - docker model
      api-key: dummy
      chat:
        model: ai/gemma3:270M-UD-Q4_K_XL
        base-url: http://localhost:12434/engines/v1   # mandatory to pass otherwise default openAi base url will be picked


    ollama:         # config for ollama - local
      chat:
        options:
          model: llama3.2:1b

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat: TRACE
    org.springframework.ai.ollama: TRACE
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics