spring:
  application:
    name: mcpclient
  ai:
    chat:
      client:
        enabled: false
    ollama:
      chat:
        options:
          model: llama3.2:1b
    mcp:
      client:
        streamable-http:
          connections:
            eazybytes:
              url: http://localhost:8081
              endpoint: /mcp

# tools not getting exposed

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.ollama: TRACE
    org.springframework.ai.chat.client.advisor: DEBUG

